"""add created_at in films-model

Revision ID: 52683d0a680a
Revises: 8f68576b930b
Create Date: 2025-01-03 16:35:57.240607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52683d0a680a'
down_revision: Union[str, None] = '8f68576b930b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('films', sa.Column('created_at', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('films', 'created_at')
    # ### end Alembic commands ###
